Function add
runteq/mokumoku pull request #46
Opened 2023-05-07 08:36 UTC by KazukiNakagawa

卒業試験試験２の機能実装のコードをそちらにお送りいたします。
下はテスト結果になります。

[![Image from Gyazo](https://i.gyazo.com/8599a8a13f18cb4e96d97007be4c330e.png)](https://gyazo.com/8599a8a13f18cb4e96d97007be4c330e)

2023-05-07 08:56 UTC, busitora requested changes
コメントしました！

2023-05-07 08:56 UTC, busitora commented on app/views/profiles/show.html.erb
> +        <%- relationship = current_user.relationships.find_by(follow_id: @user.id) %>
view で find_by するのではなく renderする前で インスタンス変数にセットする(モデルかコントローラーにて)ようにしてください

2023-05-07 08:56 UTC, busitora commented on app/views/profiles/show.html.erb
> +          <%= link_to 'フォローを外す', "#", onclick: "document.querySelector('#edit_relationship_#{relationship.id}').submit()", class: 'btn btn-danger btn-block'  %>
document.querySelector を使っている理由はなんですか? 使わないと実装できませんでしたか?

2023-05-07 08:56 UTC, busitora commented on app/views/profiles/show.html.erb
> +        <%= form_for(current_user.relationships.build) do |f| %>
form_with にしたいですね！

2023-05-07 08:56 UTC, busitora commented on spec/decorators/profile_decorator_spec.rb
> +
不要なら削除してください！

2023-05-07 08:56 UTC, busitora commented on spec/requests/profiles_spec.rb
> +RSpec.describe "Profiles", type: :request do
不要なら削除してください！

2023-05-07 09:28 UTC, KazukiNakagawa commented on spec/requests/profiles_spec.rb
> +RSpec.describe "Profiles", type: :request do
削除するとテストを実行する際にエラーが発生してしまいます。

2023-05-07 09:28 UTC, KazukiNakagawa commented on spec/decorators/profile_decorator_spec.rb
> +
削除するとテストを実行する際にエラーが発生してしまいます。

2023-05-07 09:29 UTC, KazukiNakagawa commented on app/views/profiles/show.html.erb
> +          <%= link_to 'フォローを外す', "#", onclick: "document.querySelector('#edit_relationship_#{relationship.id}').submit()", class: 'btn btn-danger btn-block'  %>
お疲れ様です。
document.querySelector を使わないとフォロー機能が実装できません。

2023-05-08 08:59 UTC, KazukiNakagawa commented on app/views/profiles/show.html.erb
> +          <%= link_to 'フォローを外す', "#", onclick: "document.querySelector('#edit_relationship_#{relationship.id}').submit()", class: 'btn btn-danger btn-block'  %>
document.querySelector を使わなくても実装できました実装できました。

2023-05-08 10:14 UTC, busitora approved these changes
LGTM

2023-05-08 10:14 UTC, busitora commented on spec/decorators/profile_decorator_spec.rb
> +
なるほど? であれば一旦大丈夫です!

2023-06-14 02:42 UTC, closed without merging